import Navbar from "@/components/UI/Navbar";

import "./globals.css";
import Footer from "@/components/UI/Footer";

export const metadata = {
  title: "EXIN",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
