import "./globals.css";

export const metadata = {
  title: "EXIN",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="container">{children}</body>
    </html>
  );
}
